apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-web
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    app: web
